# 配置服务端口号
server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://110.41.167.9:3306/db_spzx?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    url: jdbc:mysql://localhost:3306/db_spzx?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    #    password: 555086315
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 1800000 # 30 minutes
      idle-timeout: 600000 # 10 minutes
      connection-timeout: 30000 # 30 seconds
  # Redis的相关配置
  data:
    redis:
      #      host: 110.41.167.9
      host: localhost
      port: 6379
  #      password: 555086315

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml

# 自定义配置
zx:
  # （拦截器的放行路径）
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
# （文件服务器路径）
  minio:
    endpointUrl: http://110.41.167.9:9000
    accessKey: liboyang
    secreKey: 555086315
    bucketName: zx-bucket
