server:
  port: 8514

spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://110.41.167.9:3306/db_spzx?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    url: jdbc:mysql://localhost:3306/db_spzx?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
#    password: 555086315
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 1800000 # 30 minutes
      idle-timeout: 600000 # 10 minutes
      connection-timeout: 30000 # 30 seconds
  data:
    redis:
#      host: 110.41.167.9
      host: localhost
      port: 6379
#      password: 555086315

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*/*.xml