server:
  port: 8511 # 设置服务器的端口号

spring:
  application:
    name: service-product # 设置 Spring 应用的名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置 Nacos 服务发现的服务器地址
  datasource:
    type: com.zaxxer.hikari.HikariDataSource # 指定数据源类型为 HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver # 设置 MySQL JDBC 驱动程序
    #    url: jdbc:mysql://110.41.167.9:3306/db_spzx?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    url: jdbc:mysql://localhost:3306/db_spzx?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    #    password: 555086315
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 1800000 # 30 minutes
      idle-timeout: 600000 # 10 minutes
      connection-timeout: 30000 # 30 seconds

  # Redis的相关配置
  data:
    redis:
      #      host: 110.41.167.9
      host: localhost
      port: 6379
  #      password: 555086315

mybatis:
  config-location: classpath:mybatis-config.xml # 指定 MyBatis 配置文件的位置
  mapper-locations: classpath:/mapper/*/*.xml # 指定 MyBatis 映射文件的位置
